function(SCE_VCU_FreeRTOS_default_assemble_rule target)
    set(inputVar "${ASSEMBLER_PRE};-g;-mprocessor=32MK1024MCM064;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST},-I${CMAKE_CURRENT_SOURCE_DIR}/../../../src/config/default;-mdfp=/home/pedroferreira/.mchp_packs/Microchip/PIC32MK-MC_DFP/1.11.151")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../src/config/default;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/include;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/include;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK,")
endfunction()
function(SCE_VCU_FreeRTOS_default_assembleWithPreprocess_rule target)
    set(inputVar "${MP_EXTRA_AS_PRE};-g;-mprocessor=32MK1024MCM064;-DXPRJ_default=default;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST},-I${CMAKE_CURRENT_SOURCE_DIR}/../../../src/config/default")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../src/config/default;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/include;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/include;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK,")
endfunction()
function(SCE_VCU_FreeRTOS_default_compile_rule target)
    set(inputVar "${CC_PRE};-g;-x;c;-c;-mprocessor=32MK1024MCM064;-ffunction-sections;-fdata-sections;-O1;-fno-common;-Werror;-Wall;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-mdfp=/home/pedroferreira/.mchp_packs/Microchip/PIC32MK-MC_DFP/1.11.151;${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../src;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/config/default;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/include;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK")
endfunction()
function(SCE_VCU_FreeRTOS_default_compile_cpp_rule target)
    set(inputVar "${CC_PRE};-g;-mprocessor=32MK1024MCM064;-frtti;-fexceptions;-fno-check-new;-fenforce-eh-specs;-ffunction-sections;-O1;-fno-common;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-mdfp=/home/pedroferreira/.mchp_packs/Microchip/PIC32MK-MC_DFP/1.11.151;${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../src;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/config/default;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/include;${CMAKE_CURRENT_SOURCE_DIR}/../../../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK")
endfunction()
function(SCE_VCU_FreeRTOS_default_link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-g;-mprocessor=32MK1024MCM064;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-Wl,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_LD_POST},--script=${SCE_VCU_FreeRTOS_default_LINKER_SCRIPT},,--defsym=_min_heap_size=512,,--no-code-in-dinit,,--no-dinit-in-serial-mem,,--memorysummary,memoryfile.xml;-mdfp=/home/pedroferreira/.mchp_packs/Microchip/PIC32MK-MC_DFP/1.11.151")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
